// Generated by CoffeeScript 1.12.2
(function() {
  var average_word, count_characters, count_words, longest_word, replace_words, user_input, word_count;

  user_input = '';

  word_count = 0;

  count_characters = function() {
    var char_count, characters, i, len, x;
    char_count = 0;
    for (i = 0, len = user_input.length; i < len; i++) {
      x = user_input[i];
      char_count += 1;
    }
    characters = document.getElementById('characters_info');
    return characters.innerHTML = 'Characters: ' + char_count;
  };

  count_words = function() {
    var words;
    user_input = user_input.replace(/(^\s*)|(\s*$)/gi, "");
    user_input = user_input.replace(/[ ]{2,}/gi, " ");
    user_input = user_input.replace(/\n /, "\n");
    word_count = user_input.split(' ').length;
    words = document.getElementById('words_info');
    return words.innerHTML = 'Words: ' + word_count;
  };

  longest_word = function() {
    var i, len, longest, longestword, words, x;
    user_input = user_input.replace(/(^\s*)|(\s*$)/gi, "");
    user_input = user_input.replace(/[ ]{2,}/gi, " ");
    user_input = user_input.replace(/\n /, "\n");
    words = user_input.split(' ');
    longest = '';
    for (i = 0, len = words.length; i < len; i++) {
      x = words[i];
      x = x.replace(/[^A-Z]/gi, "");
      if (x.length > longest.length) {
        longest = x;
      }
    }
    longestword = document.getElementById('long_word_info');
    return longestword.innerHTML = 'Longest Word: ' + longest;
  };

  average_word = function() {
    var averageword, char_total, i, len, words, x;
    user_input = user_input.replace(/(^\s*)|(\s*$)/gi, "");
    user_input = user_input.replace(/[ ]{2,}/gi, " ");
    user_input = user_input.replace(/\n /, "\n");
    words = user_input.split(' ');
    char_total = 0;
    for (i = 0, len = words.length; i < len; i++) {
      x = words[i];
      x = x.replace(/[^A-Z]/gi, "");
      char_total += x.length;
    }
    averageword = document.getElementById('avg_word_info');
    return averageword.innerHTML = 'Avg. Word Length: ' + ("" + ((char_total / word_count).toFixed(2)));
  };

  replace_words = function() {
    var replaced_words, words_to_replace, x, y;
    words_to_replace = user_input.split(' ');
    words_to_replace = String(words_to_replace);
    replaced_words = user_input;
    for (x in replacements) {
      y = replacements[x];
      if (words_to_replace.indexOf(y) >= 0) {
        replaced_words = replaced_words.replace(y, x);
      }
    }
    return document.getElementById('converted_textarea').value = replaced_words;
  };

  analyze_button.onclick = function() {
    user_input = document.getElementById('user_textarea').value;
    count_characters();
    count_words();
    longest_word();
    average_word();
    return replace_words();
  };

}).call(this);
